#!/bin/bash

[[ -d /etc/postgresql/15/ ]] || {
	pg_createcluster 15 main
	echo "listen_addresses = 'localhost'" >> /etc/postgresql/15/main/postgresql.conf
	echo "host all all ::0/64 trust" > /etc/postgresql/15/main/pg_hba.conf
	service postgresql start
	psql -h localhost -U postgres -d postgres -c "ALTER USER postgres PASSWORD '${POSTGRES_PASSWORD}'"
	sed -i 's/trust/md5/' /etc/postgresql/15/main/pg_hba.conf
}

chmod 777 /var/www/mantisbt-2.27.0/config/
service ssh start
service postgresql restart
service php8.2-fpm start
service nginx start
sleep infinity
