#!/bin/bash

[[ -e /home/tunnel/.ssh/authorized_keys ]] || {
	ssh-keygen -C tunnel -t ed25519 -a 100 -N "${SSH_PASSWORD}" -f /home/tunnel/.ssh/mantis_ed25519
	mv /home/tunnel/.ssh/mantis_ed25519.pub /home/tunnel/.ssh/authorized_keys
}

chmod 777 /var/www/mantisbt-2.27.0/config/
service ssh start
service php8.2-fpm start
service nginx start
sleep infinity
