version: '3'

services:
  mantis:
    container_name: mantisbt
    image: anarchotect/mantisbt
    restart: always
    environment:
      SSH_PASSWORD: YourSecureSSHPassword
    ports:
      - 192.168.1.1:443:443
      - 192.168.1.1:80:80
      - 192.168.1.1:222:22
    volumes:
      - /srv/mantisbt/ssh/:/home/tunnel/.ssh/
      - /srv/mantisbt/conf/:/var/www/mantisbt-2.27.0/config/

  mantisdb:
    container_name: mantisdb
    image: postgres:15.10-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourSecurePostgresPassword
    volumes:
      - /srv/mantisbt/db/:/var/lib/postgresql/data/